name: magic_pinecone
description: "A new Flutter project."
publish_to: "none"
version: 0.0.2

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  dio: ^5.11.1
  retrofit: ^4.10.0
  logger: ^2.8.0
  json_annotation: ^4.12.0
  flutter_inappwebview: ^6.2.0-beta.3
  material_symbols_icons: ^4.2960.0
  flutter_chat_core: ^2.0.0
  flutter_chat_ui: ^2.0.0
  font_awesome_flutter: ^11.0.0
  url_launcher: ^6.3.2
  flutter_riverpod: ^3.3.2
  riverpod_annotation: ^4.0.3

  git_hooks: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  retrofit_generator: ^10.2.11
  build_runner: ^2.16.1
  json_serializable: ^6.14.1
  riverpod_generator: ^4.0.4
  riverpod_lint: ^3.1.4

flutter:
  uses-material-design: true
